name: Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --alluredir=./allure-results tests
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: ./allure-results

  generate_report:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: allure-results
          path: ./allure-results

      - name: Set up Allure
        run: |
          wget --no-check-certificate https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.zip
          unzip allure-2.13.8.zip -d /opt/
          echo "/opt/allure-2.13.8/bin" >> $GITHUB_PATH

      - name: Generate Allure report
        run: |
          allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report

  deploy_report:
    runs-on: ubuntu-latest
    needs: generate_report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Allure report
        uses: actions/download-artifact@v2
        with:
          name: allure-report
          path: ./allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ALLURE_SECRET }}
          publish_dir: ./allure-report
